name: cuddly-waddle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - python-dotenv
  - pip
  - pip:
    - langchain==0.3.16
    - langchain-core==0.3.32
    - langchain-anthropic==0.3.4
    - anthropic==0.45.2
    - wikipedia-api==0.6.0